### PR TITLE
roughed up a cli like interface

### PR DESCRIPTION
**Pull request by bunnegirl**
hi there, i wanted to make a better web interface for fend, this is my attempt to rough that up.

i think this would be suited for embedding in an iframe on the website, rather than being the website itself, but it should definitely work stand alone as well.

i want to finish it however i've run into an issue. not that i had a deep look into this, but there doesn't seem to be a way to maintain the stack between evaluations?

anyhow, let me know what you think, and if there's an easy way to solve that issue.

https://bunnegirl.github.io/fend-website/

### CODE REVIEW

**Comment by printfn** [comment]
Wow, that looks incredible!! Thank you so much for implementing this!

Currently maintaining variables and things like that is done with an extremely hacky workaround, using the [`evaluate_fend_with_timeout_multiple`](https://github.com/printfn/fend/blob/main/wasm/src/lib.rs#L74) function, but that requires passing in all the separate statements at once which unfortunately isn't going to work for this CLI-like interface. You can see an example of this weird approach in [Micropad](https://github.com/MicroPad/MicroPad-Core), in [this piece of code](https://github.com/MicroPad/MicroPad-Core/blob/bf521852b4f1332c31aa559faddf442946304073/app/src/app/components/note-viewer/elements/markdown/MarkdownTransformers.ts#L6).

I haven't looked into the issue too much, but I assume it'll be necessary to maintain the variable state either in Rust directly, or alternatively find some way to serialize it and pass it back to JavaScript. I'll try and find some time over the next couple days to try and implement the missing API in `fend-wasm`. You could also have a try implementing this yourself, and take a look in [fend-wasm/lib.rs](https://github.com/printfn/fend/blob/main/wasm/src/lib.rs) and [fend-core/lib.rs](https://github.com/printfn/fend/blob/main/core/src/lib.rs), but the code for all that is quite horrible unfortunately.

**Comment by bunnegirl** [comment]
i'm not super familiar with using wasm from rust, how hard would it be to allow javascript to fetch a new `Context`?

for now i'll do it the hacky way, it's not so bad really.

**Comment by bunnegirl** [comment]
finished the hacky solution, works fine enough for what it is. here's the iframe embeddable version:

https://bunnegirl.github.io/fend-website/widget.html

**Comment by printfn** [comment]
Awesome, thanks so much for implementing all that! I'll go ahead and merge this into the main repo.

**Comment by printfn** [comment]
All done, it's now merged, and live on <https://printfn.github.io/fend-website/>!

**Pull request closed without merging**
